version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16
commands:
  tester:
    description: "testing"
    parameters:
      test_param:
        type: string
        default: "tested"
    steps:
      - run:
          name: Execute Test
          command: |   
              echo "Hello Dave..."
              echo "I feel << parameters.test_param >>."
              aws s3api list-buckets 
  lamda_zip_and_ship:
    description: "Build lambda zip and ship to s3"
    parameters:
      s3_bucket:
        type: string
        default: "tested"
    steps:
      - run:
          name: Execute Test
          command: |   
              export SOLUTION_NAME=tgw-stno-lambdas # name of the solution
              export DIST_OUTPUT_BUCKET=<< parameters.s3_bucket >> # bucket where customized code will reside 
              export VERSION=v0.0.1 # version number for the customized code 

              cd deployment
              chmod +x ./build-s3-dist.sh
              ./build-s3-dist.sh $DIST_OUTPUT_BUCKET $SOLUTION_NAME $VERSION


jobs:
  test:
    executor: 
      name: aws-cli/default
      python-version: "3.7.6"
      debian-release: "stretch"

    steps: 
      - checkout
      - aws-cli/setup:
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          configure-default-region: true
      - tester:
          test_param: "Boo YAH"
      - lamda_zip_and_ship
          s3_bucket: "tgw-stno-lambdas"
      
   

workflows:
  version: 2
  test-workflow:
    jobs:
      - test    
          
              