version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.16
commands:
  test:
    description: "testing"
    parameters:
      test_param:
        type: string
        default: "tested"
    steps:
      - run:
          name: Execute Test
          command: |   
              echo "Hello Dave..."
              echo "I feel << parameter.test >>."
jobs:
  deploy-templates:
    executor: aws-cli/default
      python-version: 3.8
    steps: 
      - checkout
      - aws-cli/setup:
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          configure-default-region: true
   

workflows:
  version: 2
  aws-cli:
    jobs:
      - test    
          
              